syntax = "proto3";

option optimize_for = LITE_RUNTIME;

package test;

message fdr_sample {
  uint64 TimeStamp = 1; // Time at which this sample was captured
  string ParamType = 2;  // Type of this sample Uint64|String|Binary etc.
  string ParamName = 3;  // Name of this sample eg. CPU0_TEMP, GPU0_APPCLOCK etc.
  oneof ParamValue {     // Value of this sample
    string ParamValueString = 4; // Applicable when InfoType==string
    int64 ParamValueInt64 = 5;   // Applicable when InfoType==Uint64
  }
}