syntax = "proto3";

package fdrpb;

message fdr_sample {
  uint64 TimeStamp = 1; // Time at which this sample was captured
  oneof ParamValue {     // Value of this sample
    string ParamValueString = 2; // Applicable when InfoType==string
    int64 ParamValueInt64 = 3;   // Applicable when InfoType==Uint64
  }
  optional uint64 ParamID = 4; // Unique parameter ID (Used to identify parameter name)
}

message fdr_stat {
  int64 FromTime = 1;   // Start of time period within which samples lie
  int64 ToTime = 2;     // End of time period within which samples lie
  int64 NumSamples = 3; // Number of samples this stat took into consideration
  int64 Min = 4;        // Minimum value seen across all samples
  int64 Max = 5;        // Maximum value seen across all samples
  int64 Avg = 6;        // Average values for the sample set
  optional uint64 ParamID = 7; // Unique parameter ID (Used to identify parameter name)
}

message fdr_params {
  string CompClass = 1; // e.g. GPU, NVSWITCH, FPGA etc.
  string ParamClass = 2; // e.g. Config, Inventory etc.
  string ParamName = 3; // e.g. VENDOR, CURR-CLK-MEM etc.
  optional uint64 ParamID = 4; // Unique parameter ID (Used to identify parameter name)
  string ParamType = 5;  // Type of this sample Uint64|String|Binary etc.
  string ParamUnit = 6; // Unit of the sample, e.g. Celsius, Hz, Watts etc.
  string ParamNotes = 7; // Additional notes about the parameter
}

message fdr_book_of_errors {
  string BootId = 1; // Boot Index/Counter of the Host
  string DeviceType = 2; // type of device on which error occured [should be same as Sections.ID like, GPU, NVSwitch, Retimer, etc]
  string DeviceInstance = 3; // device instance on which error occured [should be same as Sections.Components.ID like, GPU0,GPU1, NVSwitch0, Retimer1, etc]
  string ErrorType = 4; // type of error [may be of type Threshold, Fault, PCIe, etc]
  uint64 ParamID = 9999; // Unique parameter ID (Used to identify parameter name)
  uint64 ErrorOccurTimeStamp = 5; // Time at which this error occured
  optional uint64 StartHifiTimeStamp = 6; // (optional) ErrorOccurTimeStamp - HiFi-Data-Preserve-Time
  optional uint64 StopHifiTimeStamp = 7; // (optional) ErrorOccurTimeStamp + HiFi-Data-Preserve-Time
}