syntax = "proto3";

package fdrpb;

message fdr_sample {
  uint64 TimeStamp = 1; // Time at which this sample was captured
  oneof ParamValue {     // Value of this sample
    string ParamValueString = 2; // Applicable when InfoType==string
    int64 ParamValueInt64 = 3;   // Applicable when InfoType==Uint64
  }
  optional uint64 ParamID = 4; // Unique parameter ID (Used to identify parameter name)
}

message fdr_stat {
  uint64 FromTime = 1;   // Start of time period within which samples lie
  uint64 ToTime = 2;     // End of time period within which samples lie
  int64 NumSamples = 3; // Number of samples this stat took into consideration
  int64 Min = 4;        // Minimum value seen across all samples
  int64 Max = 5;        // Maximum value seen across all samples
  int64 Avg = 6;        // Average values for the sample set
  uint64 MinValTimeStamp = 7; // Time at which MINIMUM value occured during this samples
  uint64 MaxValTimeStamp = 8; // Time at which MAXIMUM value occured during this samples
  optional uint64 ParamID = 9; // Unique parameter ID (Used to identify parameter name)
}

message fdr_params {
  string CompClass = 1; // e.g. GPU, NVSWITCH, FPGA etc.
  string ParamClass = 2; // e.g. Config, Inventory etc.
  string ParamName = 3; // e.g. VENDOR, CURR-CLK-MEM etc.
  optional uint64 ParamID = 4; // Unique parameter ID (Used to identify parameter name)
  string ParamType = 5;  // Type of this sample Uint64|String|Binary etc.
  string ParamUnit = 6; // Unit of the sample, e.g. Celsius, Hz, Watts etc.
  string ParamNotes = 7; // Additional notes about the parameter
}

message fdr_compactor_bookkeep {
  string CompactDirectory = 1; // name of the directory to compact throughout FDR
}

message fdr_book_of_errors {
  string BootId = 1;          // Boot Index/Counter of the Host
  string DeviceInstance = 2;  // device instance on which error occured [should be same as Sections.Components.ID like, GPU0,GPU1, NVSwitch0, Retimer1, etc]
                              // CompClass can be dervied from DeviceInstance itself. This DeviceInstance is little different than
                              // all other DeviceInstance in other message structs, where in the latter, it only holds the number 0,1, etc.
  string ErrorType = 3;       // type of error [may be of type Threshold, Fault, PCIe, etc]
  optional uint64 ParamID = 4;      // Unique parameter ID (Used to identify parameter name)
  uint64 ErrorOccurTimeStamp = 5; // Time at which this error occured
  uint64 StartHifiTimeStamp = 6;  // ErrorOccurTimeStamp - HiFi-Data-Preserve-Time
  uint64 StopHifiTimeStamp = 7;   // ErrorOccurTimeStamp + HiFi-Data-Preserve-Time
}

message fdr_event {
  uint64 EventTimeStamp = 1; // Time at which event occured
  string EventName = 2; // Type of event occured
  string EventLoggingPath = 3; // Full path of event details getting stored
}

message fdr_event_details {
  uint64 EventTimeStamp = 1; // Time at which event occured
  string EventName = 2; // Type of event occured
  string EventDeviceName = 3; // System device name
  string EventMessage = 4; // Details of event occured
  string EventOriginOfCondition = 5; // Associated device where event occurred
  string EventAdditionalInfo = 6; // Descriptive information for event
}

message fdr_boot_event {
  uint64 EventTimeStamp = 1; // Time at which FDR booted
  string HMCBootCount = 2;   // number of times HMC booted. Even though its a counter, data type is string purposefuly. 
  string UpTimeOfHMC = 3;    // uptime of HMC [output of uptime -s]
  string CurrentDate = 4;    // current date
  uint32 DataDirFormatVersion = 5;  // data/directory structure layout format followed in FDR
}
