syntax = "proto3";

package fdr;

message fdr_sample {
  uint64 TimeStamp = 1; // Time at which this sample was captured
  string ParamType = 2;  // Type of this sample Uint64|String|Binary etc.
  string ParamName = 3;  // Name of this sample eg. CPU0_TEMP, GPU0_APPCLOCK etc.
  oneof ParamValue {     // Value of this sample
    string ParamValueString = 4; // Applicable when InfoType==string
    int64 ParamValueInt64 = 5;   // Applicable when InfoType==Uint64
  }
}

message fdr_stat {
  string ParamName = 1;  // Name of this sample eg. CPU0_TEMP, GPU0_APPCLOCK etc.
  int64 FromTime = 2;   // Start of time period within which samples lie
  int64 ToTime = 3;     // End of time period within which samples lie
  int64 NumSamples = 4; // Number of samples this stat took into consideration
  int64 Min = 5;        // Minimum value seen across all samples
  int64 Max = 6;        // Maximum value seen across all samples
  int64 Avg = 7;        // Average values for the sample set
}

message fdr_params {
  string CompClass = 1; // e.g. GPU, NVSWITCH, FPGA etc.
  string ParamClass = 2; // e.g. Config, Inventory etc.
  string ParamName = 3; // e.g. VENDOR, CURR-CLK-MEM etc.
  uint64 ParamID = 4; // Unique parameter ID (Used to identify parameter name)
  string ParamType = 5;  // Type of this sample Uint64|String|Binary etc.
  string ParamUnit = 6; // Unit of the sample, e.g. Celsius, Hz, Watts etc.
  string ParamNotes = 7; // Additional notes about the parameter
}