# host info
use_local: False
local_file: ../../binary-logs.tar.gz

ip: http://127.0.0.1:2080 # host IP
username: root
password: 0penBmc

# decode option
# Note: Only one of the following options can be set as True at a time.
json: False
influx: False
sqlite: False

# json option
key_name: False

# influx option
influx_url: http://afsanac-dev-01.nvidia.com:8086/ # temporary for testing. Will be pushed to AWS later.
influx_org: NVIDIA
influx_token: 2WOusrtvMnW2ueufRaGunC6k-onEa5f1fBdkViEhTT-8-StXz9v68aDA-V-VqksCrjaSrpXWJEEop1uP0ffPfQ==

# sqlite option
append: False

# binary file format
length_delimited: False