# host info
use_local: False
local_file: /path/to/fdr-dump.tar.xz


ip: http://127.0.0.1:18889 # host IP
username: root
password: 0penBmc

# decode option
# Note: Only one of the following options can be set as True at a time.
json: True
influx: False
sqlite: False

# json option
key_name: True

# influx option
influx_url: http://afsanac-dev-01.nvidia.com:8086/ # temporary for testing. Will be pushed to AWS later.
influx_org: NVIDIA
influx_token: 2WOusrtvMnW2ueufRaGunC6k-onEa5f1fBdkViEhTT-8-StXz9v68aDA-V-VqksCrjaSrpXWJEEop1uP0ffPfQ==

# sqlite option
append: False

# binary file format
length_delimited: True

# Location/environment of the machine: Field(FIE), Factory(FAC), Default is Unknown(UNK)
environment: FAC

# Generate Coverage Report
generate_cvg_report: False
telemetry_catalog:"/path/of/telemetry_catalog.csv"  # Path to Telemetry Catalog File
telemetry_uri_exp:"/path/of/uri_expansion.csv"  # Path to Telemetry Catalog File
platform:"Blackwell-HGX-8-GPU"
exempt_list:"/path/to/nvidia-fdr/tools/data_validation/platform/exempt_telemetry_list_vulcan.yaml"        # Path to Exempt List
fdr_output_dir:""     # Path to Output the Coverage Report, If left empty Coverage will be generated in the fdr logs directory

#Generate Value Validation Report
value_validation_report: False
telemetry_agent_output:"" #path of telemetry agent output csv file
